title: Minghan Wu's Personal Website
description: From Jekyll theme cvless
baseurl: ""
url: https://MinghanWu039.github.io/MinghanWu039

theme: cvless

# site settings
taglong: Travis Wu's Personal Website
tagshort: Travis Wu

# author settings
author:
  name: Minghan Wu
  email: traviswu0524@gmail.com
photo: assets/files/photo.jpg
address: 8800 Lombard Pl, San Diego, CA
phone: 858 210 1530

# social media links
social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  x: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
