title: Minghan Wu (Travis)
description: From Jekyll theme cvless
baseurl: ""
url: https://MinghanWu039.github.io/MinghanWu039

theme: cvless

# site settings
taglong: Personal Website
tagshort: Personal Website

# author settings
author:
  name: Minghan Wu
  email: traviswu0524@gmail.com
photo: assets/files/photo.jpg
address: 8800 Lombard Pl, San Diego, CA
phone: 858 210 1530

# social media links
social:
  # facebook: username
  github: MinghanWu039
  instagram: minghanwu0524
  linkedin: minghan-wu-959876259
  # stackoverflow: 0000000/username
  # x: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
